# Generated by Django 5.2 on 2025-05-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ItemModel",
            fields=[
                ("id", models.CharField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("is_done", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField()),
            ],
        ),
    ]
