name: 🐍 Deploy Django app to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - 'djangoapi/**'
      - '.github/workflows/django.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        working-directory: djangoapi
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run tests
        working-directory: djangoapi
        run: python manage.py test todo_list.tests

  build:
    runs-on: ubuntu-latest
    needs: test
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload source as artifact
        uses: actions/upload-artifact@v4
        with:
          name: djangoapi
          path: djangoapi/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success()

    steps:
      - name: Download source artifact
        uses: actions/download-artifact@v4
        with:
          name: djangoapi

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Configure Docker to use gcloud
        run: gcloud auth configure-docker europe-west9-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t europe-west9-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/sandbox-django-artifact-registry/djangoapi:${{github.sha}} .

      - name: Push Docker image
        run: |
          docker push europe-west9-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/sandbox-django-artifact-registry/djangoapi:${{github.sha}}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: sandbox-django-service
          image: europe-west9-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/sandbox-django-artifact-registry/djangoapi:${{github.sha}}
          region: ${{ secrets.GCP_REGION }}
